# AWSTemplateFormatVersion: '2010-09-09'
# Transform: 'AWS::Serverless-2016-10-31'
# Description:  A simple backend with a RESTful API endpoint using Amazon API Gateway.
# Parameters: 
#   TableNameParameter: 
#     Type: String
# Resources:
#   handler:
#     Type: 'AWS::Serverless::Function'
#     Properties:
#       Handler: index.handler
#       Runtime: nodejs10.16.3
#       CodeUri: .
#       Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
#       MemorySize: 512
#       Timeout: 10
#       Events:
#         Api1:
#           Type: Api
#           Properties:
#             Path: /
#             Method: ANY

AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 10
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /
            Method: GET